//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("cliente_movil_rest_dotnet_conuni_gr06")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0+e72168df72874f3a502a913b8b8111c416c3677a")]
[assembly: System.Reflection.AssemblyProductAttribute("cliente_movil_rest_dotnet_conuni_gr06")]
[assembly: System.Reflection.AssemblyTitleAttribute("cliente_movil_rest_dotnet_conuni_gr06")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Android35.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Android21.0")]

// Generado por la clase WriteCodeFragment de MSBuild.

